### ISSUE TITLE
Issue running ANYmal training and play policy example according to README.md.

### ISSUE THREAD

**Issue by keeganhinnigan** [isaac-orbit/orbit.ext_template#14]
After following the README.md instructions for installing the extension template, I decided to try the example for training and playing a policy for ANYmal on flat terrain. Unfortunately, I obtained an error after copying and pasting the commands into the terminal.

**Error Message:**
```
user@user-ubuntu:~/Documents/GitHub/orbit.template$ ${ISAACSIM_PATH}/python.sh scripts/rsl_rl/train.py --task Template-Velocity-Flat-Anymal-D-v0 --num_envs 4096 --headless
Traceback (most recent call last):
  File "/home/user/Documents/GitHub/orbit.template/scripts/rsl_rl/train.py", line 43, in <module>
    app_launcher = AppLauncher(args_cli, experience=app_experience)
  File "/home/user/Documents/GitHub/orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/app/app_launcher.py", line 92, in __init__
    raise ValueError(
ValueError: Input `launcher_args` and `kwargs` both provided common attributes: {'experience'}. Please ensure that each argument is supplied to only one of them, as the AppLauncher cannot discern priority between them.
There was an error running python
```

**Comment by keeganhinnigan** [comment]
**FIXED**
Changed [scripts/rsl_rl/train.py](https://github.com/isaac-orbit/orbit.ext_template/blob/main/scripts/rsl_rl/train.py) from:
`Line 40: app_launcher = AppLauncher(args_cli, experience=app_experience)`
To:
`Line 40: app_launcher = AppLauncher(args_cli)`
